# Shared code for the character generators (gen_regent.py, gen_defect.py): reads a character's cards from the Spire
# Codex data, writes src/<name>_data.js and adds the character's names to dev/namemap.json.
import json, re, sys, subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent

KEY = {'Damage': 'dmg', 'Block': 'blk', 'Cards': 'draw', 'Energy': 'en', 'Repeat': 'hits', 'Strength': 'str', 'StrengthLoss': 'loss',
       'Vulnerable': 'vul', 'Weak': 'weak', 'CalculationBase': 'base', 'CalculationExtra': 'per', 'ExtraDamage': 'per', 'Increase': 'inc',
       'Dexterity': 'dex'}
KW = {'Exhaust': 'Burn', 'Ethereal': 'Fleeting', 'Innate': 'Opening', 'Retain': 'Retain', 'Sly': 'Furtive', 'Unplayable': 'Unplayable', 'Eternal': 'Eternal'}
TAG = {'Strike': 'Cut', 'Defend': 'Brace', 'Minion': 'Thrall'}
TARGET = {'AnyEnemy': 'enemy', 'AllEnemies': 'all', 'Self': 'self', 'None': 'self', 'RandomEnemy': 'self', None: 'self'}
# Every source file in build order; a generator loads the ones before its own character to check for id clashes.
SOURCES = ['core', 'cards', 'potions', 'monsters', 'relics', 'versions', 'combat', 'run', 'events', 'act2', 'act3', 'colorless', 'enchants',
           'events2', 'ancients', 'silent', 'neow2']

def our_id(name): return re.sub(r'[^A-Z0-9]+', '_', name.upper().replace("'", '')).strip('_')
def key(var): return KEY.get(var, var[0].lower() + var[1:])

def build(d, card_names, tokens):
    cards = {c['id']: c for c in json.load(open(d / 'cards.json'))}
    out = {}
    for orig, name in card_names.items():
        c = cards.get(orig)
        if not c: continue
        vars_ = dict(c.get('vars') or {})
        star = 'X' if c.get('is_x_star_cost') else vars_.pop('StarCost', c.get('star_cost'))
        vars_.pop('StarCost', None)
        # "XPower" duplicates "X" in the data; keep one key.
        for k in list(vars_):
            if k.endswith('Power') and k[:-5] in vars_ and vars_[k] == vars_[k[:-5]]: del vars_[k]
        v = {key(k): x for k, x in vars_.items() if isinstance(x, (int, float))}
        up, upmods = {}, set()
        for k, x in (c.get('upgrade') or {}).items():
            if k in ('add_innate', 'add_retain', 'remove_exhaust', 'remove_ethereal'): upmods.add(k); continue
            if k in ('cost', 'description_changed'): continue
            match = [vk for vk in (c.get('vars') or {}) if vk.lower() == k]
            if match and isinstance(x, str) and re.match(r'^[+-]\d+$', x):
                kk = match[0]
                if kk.endswith('Power') and kk[:-5] in (c.get('vars') or {}): kk = kk[:-5]
                up[key(kk)] = int(x)
        kw = [KW[k] for k in (c.get('keywords') or []) if k in KW]
        upkw = list(kw)
        if 'add_innate' in upmods and 'Opening' not in upkw: upkw.append('Opening')
        if 'add_retain' in upmods and 'Retain' not in upkw: upkw.append('Retain')
        if 'remove_exhaust' in upmods: upkw = [k for k in upkw if k != 'Burn']
        if 'remove_ethereal' in upmods: upkw = [k for k in upkw if k != 'Fleeting']
        cost = 'X' if c.get('is_x_cost') else (None if c['cost'] == -1 else c['cost'])
        e = {'orig': orig, 'name': name, 'rarity': 'Token' if orig in tokens else c['rarity'], 'type': c['type'],
             'cost': cost, 'target': TARGET.get(c.get('target'), 'self'),
             'kw': kw, 'tags': [TAG[t] for t in (c.get('tags') or []) if t in TAG], 'v': v, 'up': up}
        if star is not None: e['star'] = star
        if (c.get('upgrade') or {}).get('cost') is not None: e['upCost'] = c['upgrade']['cost']
        if upkw != kw: e['upKw'] = upkw
        out[our_id(name)] = e
    return out

def existing(files):
    js = ("const fs=require('fs'),vm=require('vm');const ctx=vm.createContext({console,Math});"
          f"for (const f of {json.dumps(files)}) vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),ctx);"
          "console.log(JSON.stringify({cards:Object.keys(ctx.HD.CARDS),names:Object.values(ctx.HD.CARDS).map(d=>d.name),relics:Object.keys(ctx.HD.RELICS),potions:Object.keys(ctx.HD.POTIONS)}));")
    return json.loads(subprocess.check_output(['node', '-e', js], cwd=ROOT))

def generate(data_dir, var, out_file, card_names, relic_names, potion_names, tokens, terms, before):
    data = {'0.111': build(Path(data_dir), card_names, tokens)}
    have = existing(before)
    clash = [k for k in data['0.111'] if k in have['cards']] + [our_id(n) for n in relic_names.values() if our_id(n) in have['relics']] \
        + [our_id(n) for n in potion_names.values() if our_id(n) in have['potions']] + [n for n in card_names.values() if n in have['names']]
    if clash: sys.exit(f'clash with existing content: {clash}')
    missing = [o for o in card_names if our_id(card_names[o]) not in data['0.111']]
    if missing: sys.exit(f'not in the v0.111 data: {missing}')
    (ROOT / 'src' / out_file).write_text(f'// Generated by dev/{Path(sys.argv[0]).name} from the Spire Codex data. Do not edit by hand.\n'
      f'(function () {{\n  globalThis.HD.{var} = ' + json.dumps(data, separators=(',', ':')) + ';\n})();\n')
    nm = json.load(open(ROOT / 'dev' / 'namemap.json'))
    for o, n in card_names.items(): nm['cards'][o] = our_id(n)
    for o, n in relic_names.items(): nm['relics'][o] = our_id(n)
    for o, n in potion_names.items(): nm['potions'][o] = our_id(n)
    nm['terms'].update(terms)
    json.dump(nm, open(ROOT / 'dev' / 'namemap.json', 'w'), indent=1)
    print(f"{len(data['0.111'])} cards, {len(relic_names)} relics, {len(potion_names)} potions mapped")
