# Builds src/ascension_data.js: per-monster Ascension HP (A8, Tough Enemies) and attack damage (A9, Deadly Enemies),
# for both card sets, from the Spire Codex monster data.  Usage: python3 dev/gen_ascension.py <stable eng dir> <v0.111 eng dir>
import json, sys, subprocess
from pathlib import Path
stable, beta = Path(sys.argv[1]), Path(sys.argv[2])
nm = json.load(open(Path(__file__).parent / 'namemap.json'))['monsters']
aliases = json.loads(subprocess.check_output(['node', '-e', """
const fs=require('fs'),vm=require('vm');const ctx=vm.createContext({console,Math});
for (const f of ['core','cards','potions','monsters','relics','versions','combat','run','events','act2','act3','colorless','enchants','events2','ancients','silent','neow2']) vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),ctx);
const HD=ctx.HD; const moves={}; for (const [k,d] of Object.entries(HD.MON)) moves[k]=Object.keys(d.moves);
console.log(JSON.stringify({alias: HD.MOVE_ALIASES||{}, moves}));"""], cwd=Path(__file__).parent.parent))
out = {}
for ver, d in (('stable', stable), ('0.111', beta)):
    mons = {m['id']: m for m in json.load(open(d / 'monsters.json'))}
    table = {}
    for orig, ours in nm.items():
        m = mons.get(orig)
        if not m or ours not in aliases['moves']: continue
        e = {}
        if m.get('min_hp_ascension'):
            lo = m['min_hp_ascension']; hi = m.get('max_hp_ascension') or lo
            e['hp'] = [lo, hi]
        al = aliases['alias'].get(ours, {}); rev = {v: k for k, v in al.items()}
        atk = {}
        for mv in m.get('moves') or []:
            dmg = mv.get('damage') or {}
            if dmg.get('ascension') is not None and dmg.get('normal') is not None and dmg['ascension'] != dmg['normal']:
                key = rev.get(mv['id'], mv['id'])
                if key in aliases['moves'][ours]: atk[key] = dmg['ascension']
        if atk: e['atk'] = atk
        if e: table[ours] = e
    out[ver] = table
js = ('// Generated by dev/gen_ascension.py from the Spire Codex monster data. Do not edit by hand.\n'
      '// Ascension 8 (Tough Enemies) uses hp; Ascension 9 (Deadly Enemies) uses atk per move.\n'
      '(function () {\n  globalThis.HD.ASC_MON = ' + json.dumps(out, separators=(',', ':')) + ';\n})();\n')
Path(__file__).parent.parent.joinpath('src', 'ascension_data.js').write_text(js)
print({v: {'monsters': len(t), 'with hp': sum(1 for x in t.values() if 'hp' in x), 'with atk': sum(1 for x in t.values() if 'atk' in x)} for v, t in out.items()})
